# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.2'

gem 'aasm'
gem 'active_model_serializers'
gem 'activeadmin'
gem 'activeadmin_addons'
gem 'activerecord_json_validator'
gem 'acts_as_list'
gem 'autoprefixer-rails'
gem 'blueprinter'
gem 'bootsnap', require: false
gem 'bugsnag'
gem 'bundler'
gem 'cancancan'
gem 'carrierwave'
gem 'clockwork', '~> 2.0.3'
gem 'coffee-rails'
gem 'counter_culture'
gem 'countries'
gem 'devise_token_auth'
gem 'discard'
gem 'dotenv-rails'
gem 'file_validators'
gem 'fog-aws'
gem 'geocoder'
gem 'intercom'
gem 'jwt'
gem 'kaminari'
gem 'mini_magick'
gem 'money-rails'
gem 'nokogiri'
gem 'oj'
gem 'paper_trail'
gem 'paypal-sdk-rest', '~> 1.7', '>= 1.7.2'
gem 'pg'
gem 'premailer-rails'
gem 'puma'
gem 'pundit'
gem 'rails', '5.2.3'
gem 'ransack'
gem 'redis'
gem 'responders'
gem 'roo-xls'
gem 'sassc'
gem 'sass-rails'
gem 'scout_apm'
gem 'sidekiq'
gem 'stripe'
gem 'tzinfo-data', '~> 1.2017', '>= 1.2017.3', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'uglifier'
gem 'validates_timeliness'
gem 'virtus'
gem 'webpacker', '5.0.1'
gem 'wicked_pdf', '1.1.0'
gem 'wisper', '~> 2.0'
gem 'wkhtmltopdf-binary', '~> 0.12.3.1'
gem 'wkhtmltopdf-binary-edge', '~> 0.12.5.0'
gem 'zipline'

group :development do
  gem 'foreman'
  gem 'letter_opener_web'
  gem 'listen'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'web-console'
end

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'bullet'
end

group :test do
  gem 'capybara'
  gem 'capybara-email'
  gem 'capybara-screenshot'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'fuubar'
  gem 'json-schema', '~> 2.8'
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.2'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter', '~> 0.3.0'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'spring-commands-rspec', '~> 1.0', '>= 1.0.4'
  gem 'stripe-ruby-mock'
  gem 'timecop', '~> 0.9.1'
  gem 'webmock', '~> 3.2', '>= 3.2.1'
  gem 'wisper-rspec', '~> 1.0'
  gem 'zonebie', '~> 0.6.1'
end


