name             'rg-postgresql'
maintainer       'Dmitriy Grechukha'
maintainer_email 'dmitriy.grechukha@gmail.com'
license          'All rights reserved'
description      'PostgreSQL configuration'
long_description 'PostgreSQL configuration'
version          '0.1.0'

depends 'apt'
depends 'postgresql_lwrp'
