production: &production
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
staging: &staging
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
development: &development
  adapter: redis
  url: redis://localhost:6379
test: *development
