name             'rg-monit'
maintainer       'Dmitriy Grechukha'
maintainer_email 'dmitriy.grechukha@gmail.com'
license          'All rights reserved'
description      'Monit configuration'
long_description 'Monit configuration'
version          '0.1.0'

depends 'monit'
depends 'rg-deploy'
depends 'rg-postgresql'
