name             'rg-nginx'
maintainer       'Dmitriy Grechukha'
maintainer_email 'dmitriy.grechukha@gmail.com'
license          'All rights reserved'
description      'Nginx configuration'
long_description 'Nginx configuration'
version          '0.1.0'

depends 'nginx'
depends 'rg-deploy'
