name             'rg-setup'
maintainer       'Dmitriy Grechukha'
maintainer_email 'dmitriy.grechukha@gmail.com'
license          'All rights reserved'
description      'Basic setup of the server'
long_description 'Basic setup of the server'
version          '0.1.0'

depends 'rg-firewall'
depends 'rg-hostname'
depends 'rg-oh-my-zsh'
depends 'rg-packages'
depends 'rg-ruby'
depends 'rg-sudo'
depends 'rg-swap-tuning'
depends 'rg-users'
